In [13]:
import pandas as pd

df = pd.read_excel("topic_wise_pandas_related_sentences.xlsx")
df

,Unnamed: 0,Id,AcceptedAnswerId,CreationDate,Score,ViewCount,Title,Tags,AnswerCount,CommentCount,Unnamed: 9,Unnamed: 10,Topics,Correlation Score
0,0,6467832,6468875.0,6/24/2011 12:31,16,23851,How to get the correlation between two timeser...,<python><statistics><correlation><pandas>,2,0,NaN,NaN,Topic 16,0.038462
1,1,6541123,9827848.0,6/30/2011 21:09,443,622156,Improve subplot size/spacing with many subplot...,<python><pandas><matplotlib><seaborn><subplot>,7,1,NaN,NaN,Topic 2,0.048601
2,2,7577546,7580456.0,9/28/2011 1:58,11,3739,"Using pandas, how do I subsample a large DataF...",<python><r><numpy><pandas><data.table>,1,0,NaN,NaN,Topic 13,0.038462
3,3,7837722,11617194.0,10/20/2011 14:46,379,606047,What is the most efficient way to loop through...,<python><pandas><performance><dataframe><for-l...,12,4,NaN,NaN,Topic 12,0.038462
4,4,8270129,9300391.0,11/25/2011 13:55,1,926,Pandas Panel for share portfolio,<panel><quantitative-finance><pandas>,1,0,NaN,NaN,Topic 5,0.038462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236706,236706,71544168,NaN,3/20/2022 5:00,0,16,why is inplace=True making a bug in sort_value...,<python><pandas>,3,0,NaN,NaN,Topic 17,0.038462
236707,236707,71544442,NaN,3/20/2022 6:01,0,12,`groupby` - `qcut` but with condition,<pandas><dataframe><sorting><pandas-groupby><p...,1,1,NaN,NaN,Topic 4,0.038462
236708,236708,71544483,NaN,3/20/2022 6:11,-1,11,Pandas - convert object into date format,<python><pandas><dataframe><date>,1,7,NaN,NaN,Topic 1,0.038462
236709,236709,71544523,NaN,3/20/2022 6:22,0,7,How to set maximum depth in a decision tree al...,<python><pandas><dataframe><tree><decision-tree>,0,0,NaN,NaN,Topic 20,0.038462
236710,236710,71544541,NaN,3/20/2022 6:26,0,4,Ploting time series data shows only one time s...,<python><python-3.x><pandas><matplotlib>,0,1,NaN,NaN,Topic 18,0.056213

In [14]:
df = df[['Title','Topics', 'Correlation Score']]
df

,Title,Topics,Correlation Score
0,How to get the correlation between two timeser...,Topic 16,0.038462
1,Improve subplot size/spacing with many subplot...,Topic 2,0.048601
2,"Using pandas, how do I subsample a large DataF...",Topic 13,0.038462
3,What is the most efficient way to loop through...,Topic 12,0.038462
4,Pandas Panel for share portfolio,Topic 5,0.038462
...,...,...,...
236706,why is inplace=True making a bug in sort_value...,Topic 17,0.038462
236707,`groupby` - `qcut` but with condition,Topic 4,0.038462
236708,Pandas - convert object into date format,Topic 1,0.038462
236709,How to set maximum depth in a decision tree al...,Topic 20,0.038462
236710,Ploting time series data shows only one time s...,Topic 18,0.056213

In [15]:
df = df.groupby('Topics')
df

In [16]:
df.first()

                                                      Title  Correlation Score
Topics
Topic 1   Pandas dataframe in mixed mode can't serialize...           0.038462
Topic 10   How to apply slicing on pandas Series of strings           0.038462
Topic 11  How do I read a fixed width format text file i...           0.038462
Topic 12  What is the most efficient way to loop through...           0.038462
Topic 13  Using pandas, how do I subsample a large DataF...           0.038462
Topic 14  Initializing pandas dataframes with and withou...           0.038462
Topic 15  Python map() function output into Pandas DataF...           0.038462
Topic 16  How to get the correlation between two timeser...           0.038462
Topic 17        Add indexed column to DataFrame with pandas           0.038462
Topic 18                   Pyodbc default types for numbers           0.038462
Topic 19                  Simple cross-tabulation in pandas           0.038462
Topic 2   Improve subplot size/spacing with many subplot...           0.048601
Topic 20     creating pandas data frame from multiple files           0.038462
Topic 21      Plotting a stock chart with Pandas in IPython           0.038462
Topic 22   How to take column-slices of dataframe in pandas           0.038462
Topic 23  Removing duplicates from dataframe with index ...           0.038462
Topic 24            read_csv converters for unknown columns           0.038462
Topic 25          How you create a datetime index in pandas           0.038462
Topic 26  Redefining the Index in a Pandas DataFrame object           0.038462
Topic 3                           Python Pandas Pivot Table           0.050779
Topic 4   how do I compute a weighted moving average usi...           0.050779
Topic 5                    Pandas Panel for share portfolio           0.038462
Topic 6   Python: Pandas, Dataframe, Convert 1column dat...           0.038462
Topic 7                       python: pandas install errors           0.038462
Topic 8   pandas, python - how to select specific times ...           0.038462
Topic 9   How to create high low open close chart with p...           0.057315

In [20]:
for i in range(1,27):
    mydf = df.get_group('Topic '+str(i))
    mydf = mydf.sort_values(by=['Correlation Score'], ascending=False)
    mydf.to_csv(f'Topic_{i}.csv', index=False)